---
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
require:
  - rubocop-rspec
Layout/AlignHash:
  EnforcedColonStyle: table
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineAssignmentLayout:
  EnforcedStyle: new_line
  Enabled: true
Layout/MultilineHashBraceLayout:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
  # Ignore RSpec DSL
  - spec/**/*
Naming/UncommunicativeMethodParamName:
  Enabled: false
Style/Next:
  EnforcedStyle: always
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': '[]'
    '%x': ()
Style/TrivialAccessors:
  ExactNameMatch: false
Style/SymbolArray:
  Enabled: true
Style/BarePercentLiterals:
  EnforcedStyle: percent_q
Style/CollectionMethods:
  Enabled: true
Style/Send:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/StringMethods:
  Enabled: true
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/Documentation:
  Enabled: false
Style/SignalException:
  EnforcedStyle: semantic
Style/SingleLineBlockParams:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/LambdaCall:
  Enabled: false
RSpec/MessageExpectation:
  Enabled: true
RSpec/ExampleLength:
  Enabled: false
RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
RSpec/FilePath:
  Enabled: false
